language: python

python:
 - "3.5"

env:
 - DJANGO_VERSION=3.0.3

install:
 - pip install -r requirements.txt

before_script:
 - django-admin startproject testsite .
 - ln -s zsolthajdu/stash-django/stash stash
 - echo "INSTALLED_APPS += [ 'rest_framework',  'rest_framework.authtoken', 'tagging', 'stash']" >> testsite/settings.py
 - |
    echo "REST_FRAMEWORK = { \
    'DEFAULT_PERMISSION_CLASSES': (  \
        'rest_framework.permissions.IsAuthenticated',  \
    ), \
    'DEFAULT_AUTHENTICATION_CLASSES': ( \
        'rest_framework.authentication.BasicAuthentication', \
        'rest_framework.authentication.TokenAuthentication', \
    ), \
    'DEFAULT_PAGINATION_CLASS': { 'rest_framework.pagination.PageNumberPagination' }, \
    'PAGE_SIZE': 100    }" >> testsite/settings.py
 - python manage.py migrate     
 - python manage.py makemigrations stash
 - python manage.py migrate stash
 - sed -i -e "s/^]/   path(''\, include('stash.urls')),\n]/" testsite/urls.py
 - sed -i -e "s/import path/import path,include/" testsite/urls.py
 
script:
 - python manage.py test stash.tests
 
